"use client";

import { useState, type FormEvent } from "react";

type FormStatus = "idle" | "submitting" | "success" | "error";
const inputClass = "mt-2 block w-full rounded-2xl border bg-background px-4 py-3.5 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-accent";

export default function ContactPage() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [company, setCompany] = useState(""); const [message, setMessage] = useState(""); const [status, setStatus] = useState<FormStatus>("idle"); const [feedback, setFeedback] = useState("");
  async function handleSubmit(event: FormEvent) { event.preventDefault(); if (status === "submitting") return; setStatus("submitting"); setFeedback(""); try { const res = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, email, company, message }) }); if (res.status === 201) { setName(""); setEmail(""); setCompany(""); setMessage(""); setStatus("success"); setFeedback("Thanks for getting in touch. We'll be in contact soon."); return; } let messageText = "Something went wrong. Please try again later."; try { const data = await res.json(); if (data && typeof data.error === "string" && data.error) messageText = data.error; } catch {} setFeedback(messageText); setStatus("error"); } catch { setFeedback("Something went wrong. Please try again later."); setStatus("error"); } }
  return <div className="container-shell grid gap-16 py-20 md:grid-cols-[.8fr_1.2fr] md:py-28"><div><p className="eyebrow">Start a conversation</p><h1 className="display mt-5 text-6xl font-black md:text-8xl">Bring us the brief.</h1><p className="mt-8 max-w-md text-lg leading-8 text-muted-foreground">Tell us what you&apos;re building, where it&apos;s stuck, or where you want it to go. We&apos;ll come back with a thoughtful next step.</p><div className="mt-12 border-t pt-5"><p className="eyebrow">Prefer email?</p><p className="mt-3 font-semibold">hello@heek-e.com</p></div></div><form onSubmit={handleSubmit} className="rounded-[1.5rem] border bg-card p-6 md:p-10" aria-busy={status === "submitting"}><div className="grid gap-5 sm:grid-cols-2"><div><label htmlFor="name" className="text-sm font-bold">Name</label><input id="name" required value={name} onChange={e => setName(e.target.value)} className={inputClass} /></div><div><label htmlFor="email" className="text-sm font-bold">Email</label><input id="email" type="email" required value={email} onChange={e => setEmail(e.target.value)} className={inputClass} /></div></div><div className="mt-5"><label htmlFor="company" className="text-sm font-bold">Company <span className="font-normal text-muted-foreground">(optional)</span></label><input id="company" value={company} onChange={e => setCompany(e.target.value)} className={inputClass} /></div><div className="mt-5"><label htmlFor="message" className="text-sm font-bold">What&apos;s on your mind?</label><textarea id="message" required rows={6} value={message} onChange={e => setMessage(e.target.value)} className={inputClass} /></div>{status === "success" && <p role="status" className="mt-5 rounded-2xl bg-accent p-4 text-sm font-medium">{feedback}</p>}{status === "error" && <p role="alert" className="mt-5 rounded-2xl border border-red-300 p-4 text-sm">{feedback}</p>}<button type="submit" disabled={status === "submitting"} aria-busy={status === "submitting"} className="mt-6 inline-flex w-full cursor-pointer items-center justify-center gap-2 rounded-full bg-primary px-6 py-4 font-bold text-primary-foreground transition hover:-translate-y-0.5 hover:bg-accent hover:text-accent-foreground active:translate-y-0 active:scale-[.99] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:translate-y-0 disabled:opacity-60">{status === "submitting" ? <><span aria-hidden className="h-4 w-4 animate-spin rounded-full border-2 border-primary-foreground/30 border-t-primary-foreground" />Sending…</> : <>Send message <span aria-hidden>↗</span></>}</button></form></div>;
}
